# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build by leveraging travis caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Enabling container based infrastructure hoping it will help the build speed <= this didn't work well, so it's reverted
# see https://docs.travis-ci.com/user/migrating-from-legacy/ and https://docs.travis-ci.com/user/ci-environment
sudo: true

language: java

# new workaround for https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
  hosts:
    - mockito-cd
  hostname: mockito-cd

matrix:
  include:
  - jdk: oraclejdk7
  - jdk: oraclejdk7
    env: SKIP_RELEASE=true MOCK_MAKER=mock-maker-inline
  - jdk: oraclejdk8
    env: SKIP_RELEASE=true
  - jdk: oraclejdk8
    env: SKIP_RELEASE=true MOCK_MAKER=mock-maker-inline

branches:
  #Don't build tags
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build idea -s -PcheckJava6Compatibility

after_success:
  #Releases new version:
  - ./gradlew assertReleaseNeeded && ./gradlew ciReleasePrepare && ./gradlew performRelease -Pshipkit.dryRun=false
  #Generates coverage report:
  - ./gradlew --stacktrace coverageReport && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml || echo "Code coverage failed"
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
