[versions]
bytebuddy = "1.15.3"
errorprone = "2.23.0"
junit-jupiter = "5.11.2"
junit-platform = "1.11.1"
kotlin = "2.0.20"

[libraries]
android-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
android-runner = { module = "androidx.test:runner", version = "1.6.2" }
assertj = { module = "org.assertj:assertj-core", version = "3.26.3" }
autoservice = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
bnd-gradle = { module = "biz.aQute.bnd:biz.aQute.bnd.gradle", version = "7.0.0" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
bytebuddy-android = { module = "net.bytebuddy:byte-buddy-android", version.ref = "bytebuddy" }
equinox = { module = "org.eclipse.platform:org.eclipse.osgi", version = "3.21.0" }
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-test-api = { module = "com.google.errorprone:error_prone_test_helpers", version.ref = "errorprone" }
groovy = { module = "org.codehaus.groovy:groovy", version = "3.0.22" }
hamcrest = { module = "org.hamcrest:hamcrest-core", version = "3.0" }
junit4 = { module = "junit:junit", version = "4.13.2" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.3-native-mt" }
objenesis = { module = "org.objenesis:objenesis", version = "3.3" }
opentest4j = { module = "org.opentest4j:opentest4j", version = "1.3.0" }
osgi = { module = "org.osgi:osgi.core", version = "8.0.0" }
